== 60. Selection Sort (in-place)

`selection_sort` Tar en array med tal som input och sorterar arrayen i storleksordning. Funktionen följer algoritmen för **Selection Sort**.


[WARNING]
====
Sorteringsalgoritmsuppgifterna skiljer sig lite från de andra uppgifterna i att det inte räcker att resultatet av er lösning blir rätt, ni måste också följa rätt **algoritm** för att uppnå resultatet. De automatiska testerna kontrollerar bara *resultatet*, inte *algoritmen*.

Skriv funktionen utan att använda metoderna `.sort`. Funktionen är en **in-place**-funktion, vilket innebär att den ska ändra den ursprungliga arrayen.

**VIKTIGT:** Använd endast swap-operationer (byta plats på element). Använd INTE metoder som ändrar arrayens längd som `.pop`, `.push`, `.delete`, `.insert` etc. Att ändra längden på en array är en mycket kostsam operation, och in-place sortering ska endast ändra ordningen på elementen som redan finns i arrayen.
====

[NOTE]
====
När du gör selection sort inplace, ska du hitta det minsta talet i den osorterade delen av listan, och lägga det längst bak i den sorterade delen av listan, tills den osorterade delen av listan är tom (eller den sorterade delen av listan är lika lång som hela listan)

link:https://en.wikipedia.org/wiki/Selection_sort[Wikipedia: Selection Sort]
====



[source, ruby]
.Exempelanrop
----
selection_sort([64, 25, 12, 22, 11]) #=> [11, 12, 22, 25, 64]
selection_sort([5, 3, 6, 2, 10]) #=> [2, 3, 5, 6, 10]
selection_sort([1, 2, 3, 4, 5]) #=> [1, 2, 3, 4, 5]
selection_sort([5, 4, 3, 2, 1]) #=> [1, 2, 3, 4, 5]
selection_sort([3, 0, -1, 8, 7]) #=> [-1, 0, 3, 7, 8]
----

[IMPORTANT]
====
Använd verktygen link:../goals_and_plans#indexering[indexering]
====



* Skapa ett flödesschema med penna och papper.
* Testkör flödesschemat med olika värden för att säkerställa att det fungerar.
* Implementera funktionen `selection_sort` i `selection_sort.rb`.
* Testa din lösning manuellt genom att anropa funktionen med olika argument.
* Kör de automatiska testerna med `rake` i uppgiftens rotmapp i terminalen.
